Importing the libraries

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

importing the dataset

In [24]:
header_names = ['Id number', 'refractive index', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type fo glass']
dataset = pd.read_csv('/content/glass_identification_data.csv', names=header_names)
dataset.drop(['Id number'], axis = 1, inplace=True)
dataset

refractive index     Na    Mg    Al  ...    Ca    Ba   Fe  Type fo glass
0             1.52101  13.64  4.49  1.10  ...  8.75  0.00  0.0              1
1             1.51761  13.89  3.60  1.36  ...  7.83  0.00  0.0              1
2             1.51618  13.53  3.55  1.54  ...  7.78  0.00  0.0              1
3             1.51766  13.21  3.69  1.29  ...  8.22  0.00  0.0              1
4             1.51742  13.27  3.62  1.24  ...  8.07  0.00  0.0              1
..                ...    ...   ...   ...  ...   ...   ...  ...            ...
209           1.51623  14.14  0.00  2.88  ...  9.18  1.06  0.0              7
210           1.51685  14.92  0.00  1.99  ...  8.40  1.59  0.0              7
211           1.52065  14.36  0.00  2.02  ...  8.44  1.64  0.0              7
212           1.51651  14.38  0.00  1.94  ...  8.48  1.57  0.0              7
213           1.51711  14.23  0.00  2.08  ...  8.62  1.67  0.0              7

[214 rows x 10 columns]

seprating datset into independent and dependent variables

In [25]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

spliting the dataset into training and testing set

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Applying the feature scaling

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Training the datset

In [28]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 30, criterion='entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=30,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

predicting the result

In [29]:
y_pred = classifier.predict(X_test)
print(y_pred)

[7 1 2 6 5 2 1 2 2 2 1 1 1 2 2 7 3 2 3 1 5 1 7 7 2 1 7 1 2 2 1 1 2 1 1 1 1
 3 1 7 2 6 2]


creating new dataframe

In [30]:
df = pd.DataFrame({'real value' : y_test, 'predicted value' : y_pred})
df

real value  predicted value
0            7                7
1            1                1
2            2                2
3            6                6
4            5                5
5            2                2
6            2                1
7            2                2
8            1                2
9            2                2
10           1                1
11           2                1
12           3                1
13           2                2
14           2                2
15           7                7
16           2                3
17           1                2
18           3                3
19           3                1
20           5                5
21           2                1
22           7                7
23           7                7
24           2                2
25           1                1
26           7                7
27           1                1
28           2                2
29           2                2
30           1                1
31           1                1
32           2                2
33           2                1
34           2                1
35           3                1
36           1                1
37           3                3
38           2                1
39           7                7
40           2                2
41           6                6
42           2                2

finding the accuracy of the model

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 7  2  0  0  0  0]
 [ 6 12  1  0  0  0]
 [ 3  0  2  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  6]]


0.7209302325581395

saving the prediciting results

In [32]:
csvfile = df.to_csv('predicted values.csv')